baseurl = "https://blog.xil.se/"
languageCode = "en-us"
title = "Blog"
canonifyurls = true
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 post = "/:year/:filename/"

[taxonomies]
    category = "categories"
    author = "author"

[params]
    avatar = "/images/logo.svg"
    author = "xil.se"
    rss = true
    home_mode = "posts"

[params.social]
    GitHub = "xil-se"
    Twitter = "xil_hackerspace"
    Email   = "hello@xil.se"


[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
